In [1]:
import pandas as pd

In [10]:
data = {
    "name" : ["Bhagvat","Akash","Vikas","Prashant"],
    "marks" : [80,60,65,75],
    "age" : [30,26,36,38]
}

d1 = pd.DataFrame((data))
d1

       name  marks  age
0   Bhagvat     80   30
1     Akash     60   26
2     Vikas     65   36
3  Prashant     75   38

In [ ]:
d1.head()  # by default given top 5 rows

       name  marks  age
0   Bhagvat     80   30
1     Akash     60   26
2     Vikas     65   36
3  Prashant     75   38

In [ ]:
d1.head(2) # top 2 rows

      name  marks  age
0  Bhagvat     80   30
1    Akash     60   26

In [ ]:
d1.tail(2)  # last 2 rows

       name  marks  age
2     Vikas     65   36
3  Prashant     75   38

In [ ]:
d1.shape   # give rows vs coloumns

(4, 3)

In [ ]:
d1.columns   # given total coloumn

Index(['name', 'marks', 'age'], dtype='str')

In [ ]:
d1.rename(columns={"name":"Std_Name"},inplace=True)  # check below.

In [22]:
d1

   Std_Name  marks  age
0   Bhagvat     80   30
1     Akash     60   26
2     Vikas     65   36
3  Prashant     75   38

In [ ]:
d1.describe()  # shows the numaric data calculation, like we have 1 lakha data find out avg salary-used this function.

           marks        age
count   4.000000   4.000000
mean   70.000000  32.500000
std     9.128709   5.507571
min    60.000000  26.000000
25%    63.750000  29.000000
50%    70.000000  33.000000
75%    76.250000  36.500000
max    80.000000  38.000000

In [4]:
import pandas as pd

In [21]:
df = pd.read_excel(r"C:\Users\hp\Downloads\Interview Que for DE\expenses.xlsx")
print(df)

         Date    Category                  Item   Amount
0  2024-05-01        rent              home rent     500
1  2024-05-01  Utilities               gas bill      200
2  2024-05-01  Utilities               phn bill      100
3  2024-05-01       food              groceries       50
4  2024-05-01       food        chotumal samosa       20
5  2024-05-02       food      tondumal panipuri       20
6  2024-05-02       food           olive garden       50
7  2024-05-02       food               tea post       10
8  2024-05-02       food             water bill      400
9  2024-05-03  Utilities              wifi bill     1500
10 2024-05-03       food              groceries     2000
11 2024-05-04       food   chedilal rajmachaval       50

In [ ]:
#print(df.duplicated().sum())
#print(df.sample())

0

In [22]:
df.shape
df.columns

Index(['Date', 'Category', 'Item ', 'Amount'], dtype='str')

In [23]:
# Selct Coloumn
df.columns = df.columns.str.strip()
print(df[["Item","Amount"]])      ## retrive specific coloumn

                     Item  Amount
0               home rent     500
1               gas bill      200
2               phn bill      100
3              groceries       50
4        chotumal samosa       20
5      tondumal panipuri       20
6           olive garden       50
7               tea post       10
8             water bill      400
9              wifi bill     1500
10             groceries     2000
11  chedilal rajmachaval       50

In [24]:
# select rows

df.loc[df["Category"]=="rent"]   ## gives total data of selected rows.

        Date Category       Item  Amount
0 2024-05-01     rent  home rent     500

In [34]:
# select rows in multiple
print(df.loc[(df["Category"]=="food ") & (df["Amount"]>=10)])

         Date Category                   Item  Amount
3  2024-05-01    food              groceries       50
4  2024-05-01    food        chotumal samosa       20
5  2024-05-02    food      tondumal panipuri       20
6  2024-05-02    food           olive garden       50
7  2024-05-02    food               tea post       10
8  2024-05-02    food             water bill      400
10 2024-05-03    food              groceries     2000
11 2024-05-04    food   chedilal rajmachaval       50

In [35]:
print(df.sort_values(by="Amount",ascending=False))

         Date    Category                   Item  Amount
10 2024-05-03       food              groceries     2000
9  2024-05-03  Utilities              wifi bill     1500
0  2024-05-01        rent              home rent     500
8  2024-05-02       food             water bill      400
1  2024-05-01  Utilities               gas bill      200
2  2024-05-01  Utilities               phn bill      100
3  2024-05-01       food              groceries       50
6  2024-05-02       food           olive garden       50
11 2024-05-04       food   chedilal rajmachaval       50
4  2024-05-01       food        chotumal samosa       20
5  2024-05-02       food      tondumal panipuri       20
7  2024-05-02       food               tea post       10

In [36]:
grp = df.groupby("Category")["Amount"].min()
print(grp)

Category
Utilities     100
food           10
rent          500
Name: Amount, dtype: int64

In [38]:
df2 = pd.read_csv(r"C:\Users\hp\Downloads\Interview Que for DE\Sales_Data_Practice.csv")
print(df2)
df2.dropna(inplace=True)
print(df2)

   Order ID Customer Name     City     Product   Sale Date  Quantity   Amount
0   ORD1008         Sunil   Indore       MOUSE         NaN       5.0  25000.0
1   ORD1012    Neha Verma   jaipur  Headphones  20-04-2025       1.0  20000.0
2   ORD1004  Khushbu Soni  mumbai   Headphones  20-04-2025       NaN  20000.0
3   ORD1000   Priya Singh   jaipur     Monitor  20-04-2025       1.0  20000.0
4   ORD1019    Ravi Patel   jaipur      Tablet  10-02-2025       3.0  18000.0
5   ORD1017    Ravi Patel   Indore       MOUSE  05-01-2025       3.0  18000.0
6   ORD1011   Amit Sharma  mumbai       Tablet  10-02-2025       2.0  18000.0
7   ORD1002   Amit Sharma    DELHI  Headphones  20-04-2025       1.0  18000.0
8   ORD1017    Ravi Patel   bhopal     mobile   10-02-2025       2.0  18000.0
9   ORD1011    Neha Verma     Pune      Laptop  05-01-2025       2.0  18000.0
10  ORD1002   Rahul Mehta      NaN     mobile   20-04-2025       1.0  18000.0
11  ORD1003    Neha Verma   jaipur      Laptop  20-04-2025       1.0  15000.0
12  ORD1002   Priya Singh  mumbai      mobile   05-03-2025       3.0  15000.0
13  ORD1014   Priya Singh   Indore      Laptop  20-04-2025       2.0  15000.0
14  ORD1006   Rahul Mehta   jaipur      Tablet  20-04-2025       NaN  15000.0
15  ORD1007   Rahul Mehta   bhopal     Monitor  05-03-2025       1.0  15000.0
16  ORD1003  Khushbu Soni      NaN      Tablet         NaN       2.0  15000.0
17  ORD1008   Rahul Mehta   Indore     mobile   05-03-2025       5.0  12000.0
18  ORD1015    Ravi Patel   bhopal       MOUSE  10-02-2025       NaN  12000.0
19  ORD1016   Priya Singh     Pune  Headphones  10-02-2025       5.0  12000.0
20  ORD1007    Neha Verma    DELHI     mobile   20-04-2025       2.0  12000.0
21  ORD1018  Khushbu Soni     Pune  Headphones         NaN       5.0  10000.0
22  ORD1007         Sunil      NaN       MOUSE  20-04-2025       3.0  10000.0
23  ORD1016    Neha Verma   Indore       MOUSE         NaN       5.0  10000.0
24  ORD1012  Khushbu Soni      NaN  Headphones  05-03-2025       1.0  10000.0
25  ORD1010  Khushbu Soni   Bhopal  Headphones  05-03-2025       3.0  10000.0
26  ORD1000         Sunil   Bhopal      Tablet  20-04-2025       5.0      NaN
27  ORD1003   Amit Sharma    DELHI       MOUSE  05-01-2025       3.0      NaN
28  ORD1002   Rahul Mehta      NaN     Monitor  05-03-2025       3.0      NaN
29  ORD1003    Neha Verma   bhopal     mobile   05-03-2025       2.0      NaN
   Order ID Customer Name     City     Product   Sale Date  Quantity   Amount
1   ORD1012    Neha Verma   jaipur  Headphones  20-04-2025       1.0  20000.0
3   ORD1000   Priya Singh   jaipur     Monitor  20-04-2025       1.0  20000.0
4   ORD1019    Ravi Patel   jaipur      Tablet  10-02-2025       3.0  18000.0
5   ORD1017    Ravi Patel   Indore       MOUSE  05-01-2025       3.0  18000.0
6   ORD1011   Amit Sharma  mumbai       Tablet  10-02-2025       2.0  18000.0
7   ORD1002   Amit Sharma    DELHI  Headphones  20-04-2025       1.0  18000.0
8   ORD1017    Ravi Patel   bhopal     mobile   10-02-2025       2.0  18000.0
9   ORD1011    Neha Verma     Pune      Laptop  05-01-2025       2.0  18000.0
11  ORD1003    Neha Verma   jaipur      Laptop  20-04-2025       1.0  15000.0
12  ORD1002   Priya Singh  mumbai      mobile   05-03-2025       3.0  15000.0
13  ORD1014   Priya Singh   Indore      Laptop  20-04-2025       2.0  15000.0
15  ORD1007   Rahul Mehta   bhopal     Monitor  05-03-2025       1.0  15000.0
17  ORD1008   Rahul Mehta   Indore     mobile   05-03-2025       5.0  12000.0
19  ORD1016   Priya Singh     Pune  Headphones  10-02-2025       5.0  12000.0
20  ORD1007    Neha Verma    DELHI     mobile   20-04-2025       2.0  12000.0
25  ORD1010  Khushbu Soni   Bhopal  Headphones  05-03-2025       3.0  10000.0

In [39]:
# group by
grp=df2.groupby(["City"])
for name,group in grp:
    print(name)
    print(group)
    print()

('Bhopal',)
   Order ID Customer Name    City     Product   Sale Date  Quantity   Amount
25  ORD1010  Khushbu Soni  Bhopal  Headphones  05-03-2025       3.0  10000.0

('DELHI',)
   Order ID Customer Name   City     Product   Sale Date  Quantity   Amount
7   ORD1002   Amit Sharma  DELHI  Headphones  20-04-2025       1.0  18000.0
20  ORD1007    Neha Verma  DELHI     mobile   20-04-2025       2.0  12000.0

('Indore',)
   Order ID Customer Name    City  Product   Sale Date  Quantity   Amount
5   ORD1017    Ravi Patel  Indore    MOUSE  05-01-2025       3.0  18000.0
13  ORD1014   Priya Singh  Indore   Laptop  20-04-2025       2.0  15000.0
17  ORD1008   Rahul Mehta  Indore  mobile   05-03-2025       5.0  12000.0

('Pune',)
   Order ID Customer Name  City     Product   Sale Date  Quantity   Amount
9   ORD1011    Neha Verma  Pune      Laptop  05-01-2025       2.0  18000.0
19  ORD1016   Priya Singh  Pune  Headphones  10-02-2025       5.0  12000.0

('bhopal',)
   Order ID Customer Name    City  Product   Sale Date  Quantity   Amount
8   ORD1017    Ravi Patel  bhopal  mobile   10-02-2025       2.0  18000.0
15  ORD1007   Rahul Mehta  bhopal  Monitor  05-03-2025       1.0  15000.0

('jaipur',)
   Order ID Customer Name    City     Product   Sale Date  Quantity   Amount
1   ORD1012    Neha Verma  jaipur  Headphones  20-04-2025       1.0  20000.0
3   ORD1000   Priya Singh  jaipur     Monitor  20-04-2025       1.0  20000.0
4   ORD1019    Ravi Patel  jaipur      Tablet  10-02-2025       3.0  18000.0
11  ORD1003    Neha Verma  jaipur      Laptop  20-04-2025       1.0  15000.0

('mumbai ',)
   Order ID Customer Name     City  Product   Sale Date  Quantity   Amount
6   ORD1011   Amit Sharma  mumbai    Tablet  10-02-2025       2.0  18000.0
12  ORD1002   Priya Singh  mumbai   mobile   05-03-2025       3.0  15000.0

In [40]:
grp=df2.groupby("City")
print(grp.get_group("Indore"))

   Order ID Customer Name    City  Product   Sale Date  Quantity   Amount
5   ORD1017    Ravi Patel  Indore    MOUSE  05-01-2025       3.0  18000.0
13  ORD1014   Priya Singh  Indore   Laptop  20-04-2025       2.0  15000.0
17  ORD1008   Rahul Mehta  Indore  mobile   05-03-2025       5.0  12000.0